apiVersion: apps/v1
kind: Deployment
metadata:
  name: testereplicadata5
  labels:
    app: nginx
    env: uat
  #namespace: testns
spec:
  replicas: 4
  selector:
    matchLabels:
      version: "3"
      app: pointing-it
  template:
    metadata:
      name: testtemp
      labels:
        app: pointing-it
        version: "3"
    spec:
      containers:
        - name: testcont
          image: nginx:1.23.0
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "250Mi"  # Adjust as needed
              cpu: "250m"     # Adjust as needed
            limits:
              memory: "500Mi" # Adjust as needed
              cpu: "500m"     # Adjust as needed

      
---
apiVersion: v1
kind: Service
metadata:
  name: ng-service
spec:
  selector:
    app: pointing-it
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
