pipeline {
    agent any

    environment {
      MAVEN_HOME = tool name: 'Maven 3.9.8', type: 'hudson.tasks.Maven$MavenInstallation'
        PATH = "${env.MAVEN_HOME}\\bin;${env.PATH}"
    }

    stages {
        stage('Git check out ') {
            steps{
         git (
            url: 'https://github.com/mathi686/jen-multi-branch-demo.git'
         ) 
        }
        }

        stage('maven build') {
         steps {
           script {
         bat "${MAVEN_HOME}\\bin\\
           }
         }
        }

        stage('Docker build') {
          steps {
            script {
           bat 'docker build  -t mynewtestapp:latest . '
          }
        }
        }
         
        
    }
}