apiVersion: v1
kind: Namespace
metadata:
  name: back-end

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-egress
  labels:
    app: nginx-des
    env: uat
  namespace: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      version: "3"
      app: test-pod
  template:
    metadata:
      name: testtemp
      labels:
        app: test-pod
        version: "3"
    spec:
      containers:
        - name: testcont
          image: nginx:latest
          # command: ["sh", "-c", "while true; do sleep 3600; done"]
          ports:
            - containerPort: 80
        

      

