apiVersion: apps/v1
kind: Deployment
metadata: 
  name: Nginixdeployement
  labels:
   app: nginx
spec:
  replicas: 4
  selector:
    matchLables:
      app: pointthelable
    template:
      metadata: 
        name: pod name
        lables: 
          app: pointthelable
      spec: 
        containers:
        -  name: ngcontainer
           image: nginix:lates
           ports:
             - containerport: 80
           resource:
             limits: 
              cpu: 250m
              memory: 250mi
             resqust: 
               cpu: 500m
               memory: 500mi


  

     