# apiVersion: v1
# kind: Service
# metadata:
#  name: jenkins-svc
#  annotations: 
#    serice.beta.kubernets.io/aws-loadbalancer-subnets
#      "10.0.2.0/24"10.0.1.0/24
# spec:
#   selector:
#     app: cicd-master
#   ports:
#     - port: 80
#       targetPort: 8080
#       protocol: TCP
#   type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  #annotations:
    #service.beta.kubernetes.io/aws-load-balancer-subnets: "10.0.2.0/24,10.0.1.0/24"
spec:
  selector:
    app: cicd-master
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
